# Generated by Django 2.1.2 on 2018-10-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_city_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_name', models.CharField(blank=True, choices=[('Forest_Fire', 'Forest_Fire'), ('Flood', 'Flood'), ('tora', 'tora')], max_length=130, null=True)),
                ('status', models.CharField(choices=[('Safe', 'Safe'), ('Unsafe', 'Unsafe')], max_length=130)),
            ],
        ),
    ]
