# Generated by Django 2.1.2 on 2018-10-24 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(max_length=100)),
                ('user_name', models.CharField(blank=True, max_length=120, null=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('college', models.CharField(blank=True, max_length=120, null=True)),
                ('fb_link', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
